version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lovelove_postgres
    environment:
      POSTGRES_DB: lovelove
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paiva123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
